# 📊 04 - Data Input and Output

Most of data science is about **loading data, exploring it, and saving results**.  
In this notebook you will learn:
- Reading CSV files with Pandas
- Inspecting DataFrames (`head`, `info`, `describe`)
- Writing data back to CSV
- Reading Excel files (if available)

## 1. Reading CSV Files

In [1]:
import pandas as pd

# Create a small CSV for demo
data = """Name,Age,Score
Alice,23,90
Bob,25,85
Charlie,22,95
"""
with open("students.csv", "w") as f:
    f.write(data)

# Read CSV into DataFrame
df = pd.read_csv("students.csv")
df

      Name  Age  Score
0    Alice   23     90
1      Bob   25     85
2  Charlie   22     95

✅ **Your Turn**: Create your own small CSV (3–5 rows) and read it into Pandas.

In [3]:
import pandas as pd

# Create a small dataset
data = {
    "City": ["Dallas", "Austin", "Houston", "San Antonio"],
    "Population_millions": [1.3, 1.0, 2.3, 1.5],
    "Famous_for": ["Arts District", "Live Music", "NASA", "The Alamo"]
}

df = pd.DataFrame(data)

# Save to CSV
df.to_csv("texas_cities.csv", index=False)

df

df_loaded = pd.read_csv("texas_cities.csv")
df_loaded

          City  Population_millions     Famous_for
0       Dallas                  1.3  Arts District
1       Austin                  1.0     Live Music
2      Houston                  2.3           NASA
3  San Antonio                  1.5      The Alamo

## 2. Exploring DataFrames

In [4]:
# Look at the first rows
df.head()

          City  Population_millions     Famous_for
0       Dallas                  1.3  Arts District
1       Austin                  1.0     Live Music
2      Houston                  2.3           NASA
3  San Antonio                  1.5      The Alamo

In [5]:
# Info about columns and data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   City                 4 non-null      object
 1   Population_millions  4 non-null      float64
 2   Famous_for           4 non-null      object
dtypes: float64(1), object(2)
memory usage: 224.0+ bytes

In [6]:
# Summary statistics
df.describe()

       Population_millions
count             4.000000
mean              1.525000
std               0.556028
min               1.000000
25%               1.225000
50%               1.400000
75%               1.700000
max               2.300000

✅ **Your Turn**: Use `.head()` to preview your dataset and `.describe()` to see basic statistics.

In [7]:
df_loaded.head()
df_loaded.describe()

       Population_millions
count             4.000000
mean              1.525000
std               0.556028
min               1.000000
25%               1.225000
50%               1.400000
75%               1.700000
max               2.300000

## 3. Writing CSV Files

In [8]:
# Save the DataFrame to a new CSV
df.to_csv("students_copy.csv", index=False)
%ls *.csv

students.csv       students_copy.csv  texas_cities.csv

✅ **Your Turn**: Save your DataFrame to a CSV file called `my_data.csv`.

In [9]:
df_loaded.to_csv("my_data.csv", index=False)

## 4. Reading Excel Files

In [10]:
# Optional: Requires 'openpyxl' installed
# Save to Excel
df.to_excel("students.xlsx", index=False)

# Read Excel file
pd.read_excel("students.xlsx")

ModuleNotFoundError: No module named 'openpyxl'

✅ **Your Turn**: Try saving your dataset to Excel and reading it back (if supported in your environment).

In [11]:
#save to excel
df_loaded.to_excel("my_data.xlsx", index=False)
#read back
df_from_excel = pd.read_excel("my_data.xlsx")
df_from_excel

ModuleNotFoundError: No module named 'openpyxl'

---
### Summary
- `pd.read_csv` loads data into a DataFrame.
- Use `.head()`, `.info()`, `.describe()` to explore quickly.
- `df.to_csv` and `df.to_excel` save results.
- Pandas makes file I/O simple and reliable.